# Generated by Django 4.2.5 on 2023-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodule', '0002_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='person1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='person2',
            field=models.TextField(),
        ),
    ]
