# Generated by Django 4.2.5 on 2023-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodule', '0003_alter_dialog_person1_alter_dialog_person2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('pharmacist', models.TextField()),
                ('customer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
