# Generated by Django 4.2.5 on 2023-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodule', '0005_airport_direction_restaurant_teatime_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='customer1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='customer2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='customer3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='customer4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist4',
            field=models.TextField(null=True),
        ),
    ]
