# Generated by Django 4.2.5 on 2023-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_word', models.CharField(max_length=50)),
                ('match_word', models.CharField(max_length=50)),
            ],
        ),
    ]
