# Generated by Django 4.2.5 on 2023-10-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='orignal_word',
            new_name='original_word',
        ),
    ]
