# Generated by Django 4.2.5 on 2023-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_orignal_word_word_original_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
                ('choice1', models.CharField(max_length=50)),
            ],
        ),
    ]
